apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: app-ns
  labels:
    app: project-app-iti
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: project-app-iti
